name: Push File

on:
  workflow_dispatch:

jobs:
  copy-file:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Allow Illegal Access
      run: set MAVEN_OPTS=--illegal-access=permit
    - name: Build with Maven
      run: set MAVEN_OPTS=--illegal-access=permit & mvn --batch-mode --update-snapshots verify
    - name: Pushes to another repository
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'target'
        destination-github-username: 'sunarya-thito'
        destination-repository-name: 'NodeFlow'
        user-email: septogeddon@gmail.com
        target-branch: deploy
