# This is a basic workflow to help you get started with Actions

name: Generate JDK 16 Docs

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  generate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Generate Docs
        run: mvn nodeflow-build-helper:generate-docs -DjavaDocsUrl="https://docs.oracle.com/en/java/javase/16/docs/api/" -DoutputDirectory="Generated Docs/JDK 16/"
      - name: Publish Docs
        uses: cpina/github-action-push-to-another-repository@v1.3
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: target
          destination-github-username: sunarya-thito
          destination-repository-name: GeneralizedJavaDocs
          target-branch: jdk-16
          user-email: septogeddon@gmail.com
